ldlidar_publisher_ld14:
  ros__parameters:
    product_name: LDLiDAR_LD14
    laser_scan_topic_name: scan
    point_cloud_2d_topic_name: pointcloud2d
    frame_id: base_laser
    port_name: /dev/serial0
    serial_baudrate: 115200
    laser_scan_dir: true
    enable_angle_crop_func: false
    angle_crop_min: 135.0
    angle_crop_max: 225.0
